version: '3'
services:
  database:
    image: wnameless/oracle-xe-11g
    ports:
      - "49160:22"
  precise:
    build:
      context: ./docker-image
      args:
        ubuntu_version: precise
    volumes:
      - ./build/precise:/host
    depends_on:
      - database
  trusty:
    build:
      context: ./docker-image
      args:
        ubuntu_version: trusty
    volumes:
      - ./build/trusty:/host
    depends_on:
      - database
  xenial:
    build:
      context: ./docker-image
      args:
        ubuntu_version: xenial
    volumes:
      - ./build/xenial:/host
    depends_on:
      - database
  bionic:
    build:
      context: ./docker-image
      args:
        ubuntu_version: bionic
    volumes:
      - ./build/bionic:/host
    depends_on:
      - database
