version: '2'
services:
  database:
    image: wnameless/oracle-xe-11g
    ports:
      - "49160:22"
  precise:
    build: precise/
    volumes:
      - .:/host
    depends_on:
      - database
  trusty:
    build: trusty/
    volumes:
      - .:/host
    depends_on:
      - database
