version: '3'
services:
  database:
    image: wnameless/oracle-xe-11g
    ports:
      - "49160:22"
  precise:
    build:
      context: ./docker-image
      args:
        ubuntu_version: precise
        php_packages: php5 php5-cli php5-dev php-db php-pear
        oci8_pecl_version: oci8-2.0.12
    volumes:
      - ./build/precise:/host
    depends_on:
      - database
  trusty:
    build:
      context: ./docker-image
      args:
        ubuntu_version: trusty
        php_packages: php5 php5-cli php5-dev php-db php-pear
        oci8_pecl_version: oci8-2.0.12
    volumes:
      - ./build/trusty:/host
    depends_on:
      - database
  xenial:
    build:
      context: ./docker-image
      args:
        ubuntu_version: xenial
        php_packages: php7.0 php7.0-cli php7.0-dev
        oci8_pecl_version: oci8-2.1.2
    volumes:
      - ./build/xenial:/host
    depends_on:
      - database
