version: '3'
services:
  database:
    image: wnameless/oracle-xe-11g
    ports:
      - "49160:22"
  precise:
    build:
      context: ./docker-image
      args:
        ubuntu_version: precise
        php_packages: php5 php5-cli php5-dev php-db php-pear
    volumes:
      - ./build/precise:/host
    depends_on:
      - database
  trusty:
    build:
      context: ./docker-image
      args:
        ubuntu_version: trusty
        php_packages: php5 php5-cli php5-dev php-db php-pear
    volumes:
      - ./build/trusty:/host
    depends_on:
      - database
  xenial:
    build:
      context: ./docker-image
      args:
        ubuntu_version: xenial
        php_packages: php7.0 php7.0-cli php7.0-dev
    volumes:
      - ./build/xenial:/host
    depends_on:
      - database
  bionic:
    build:
      context: ./docker-image
      args:
        ubuntu_version: bionic
        php_packages: php7.2 php7.2-cli php7.2-dev
    volumes:
      - ./build/bionic:/host
    depends_on:
      - database
